throttle_period: 1.0 # seconds
transform_lookup_timeout: 0.3 # seconds
separate_cluster_removal_period: 0.1 # seconds
pointcloud_threads: 1

ground_points_max_distance: 0.7 # metres
# at least the number of voxels in the xy plane times this ratio of points have to be considered background
# before classification may begin
background_sufficient_points_ratio: 0.15

operation_area:
  offset: # offset of the box center relative to the global origin
    x: 5.0 # meters
    y: -20.0 # meters
    z: -2.0 # meters - this is the lowest value, not center
  size:
    x: 60.0 # meters
    y: 50.0 # meters
    z: 15.0 # meters

output:
  position_sigma: 0.1

sensor:
  # Ouster OS0-128 Gen2
  vertical_fov_angle: !degrees 90.0
  vertical_rays: 128
  horizontal_rays: 2048
  # # Ouster OS1-128 Gen2
  # vertical_fov_angle: !degrees 45.0
  # vertical_rays: 128
  # horizontal_rays: 2048
  # Ouster OS1-16 Gen1
  # vertical_fov_angle: !degrees 33.2
  # vertical_rays: 16
  # horizontal_rays: 2048

voxel_map:
  # Each voxel holds a value x, which is updated using a new value y according
  # to the formula x := (x + y)/2
  voxel_size: 0.25 # metres
  # Voxels are updated using these scores
  scores:
    # Each voxel is initialized to this value at the beginning
    init: -700.0
    # A voxel with a point in it, which is in a cluster classified as part of background,
    # is updated using this value
    point: 0.0
    # A voxel with a point in it, which is in a cluster classified as unknown, is updated
    # using this value
    unknown: -740.0
    # A voxel with a ray going through it is updated using this value (unless there is
    # a background or unknown point in the voxel as well)
    ray: -1000.0
  # Voxels are classified according to these thresholds
  thresholds:
    # Voxels with a value higher than this are considered part of the static apriori map
    apriori_map: 0.0
    # Voxels with a value higher than this are considered to be *sure* (or confirmed)
    # parts of the background when looking for disconnected background clusters
    # which are to be suppressed
    sure_obstacles: -0.1
    # Voxels with a value higher than this (and lower than the value for apriori_map)
    # are considered to be new obstacles (not apriori known)
    new_obstacles: -300.0
    # Voxels with a value higher than this (and lower than the value for new_obstacles)
    # are considered to be frontiers. If all voxels around a voxel (including it) have
    # a value lower than this, it is considered to be certainly floating. If all voxels
    # corresponding to points in a cluster are floating, it is considered to be a detection.
    frontiers: -750.0

classification:
  # cluster with less point than this number are ignored
  min_points: 4
  # clusters with bounding box diagonal size larger than this will never be classified as MAV
  max_size: 3.0 # meters
  # clusters further than this are ignored
  max_distance: 18.0 # meters
  # when looking for a connection of a cluster to the ground, a neighborhood of maximally this distance will be considered
  max_explore_distance: 3.0 # meters

raycast:
  pause: false
  max_distance: 20.0 # meters
  weight_coefficient: 0.75
  min_intensity: 0
  mask_rows: 128

sepclusters:
  pause: false
  min_sure_points: 24

# points inside the box, defined by *uav_exclude_box*, relative to the sensor, are discarded
# this is used to filter out the MAV itself from the pointcloud
exclude_box:
  offset: # offset of the box center relative to the sensor origin
    x: 0.09 # meters
    y: 0.0 # meters
    z: -0.75 # meters
  size:
    x: 2.0 # meters
    y: 2.0 # meters
    z: 1.5 # meters
