transform_lookup_timeout: 0.3 # seconds
throttle_period: 0.1 # seconds

constraints:
  u: 5.0 # meters per second
  omega: 1.5 # radians per second

control:
  enabled: false
  use_noise: true
  repeat_commands: false
  repeat_rate: 10 # Hz
  admissible_overshoot_probability: 0.3
  proportional_constant: 0.6

formation:
  update: false
