transform_lookup_timeout: 0.3 # seconds
throttle_period: 0.1 # seconds

control:
  enabled: false
  use_noise: true
  repeat_commands: false
  repeat_rate: 10 # Hz
  admissible_overshoot_probability: 0.05
  proportional_constant: 0.6

formation:
  update: false
