transform_lookup_timeout: 0.3 # seconds
throttle_period: 0.1 # seconds

control:
  admissible_overshoot_probability: 0.3
  proportional_constant: 0.4

formation:
  uav1:
    uvdar_id: 0
    position: [0.0, 0.0, 0.0]
    heading: 0.0
  uav2:
    uvdar_id: 1
    position: [4.0, 2.0, 0.0]
    heading: 0.0
