transform_lookup_timeout: 0.3 # seconds
throttle_period: 1.0 # seconds

formation:
  uav1:
    uvdar_id: 0
    position: [0.0, 0.0, 0.0]
    heading: 1.57
  uav2:
    uvdar_id: 1
    position: [3.0, 0.0, 0.0]
    heading: 0.0
